import type { Spec, Endpoint, TypeDef, ResponseDef } from '@zwaggen/core';
import { tagForEndpoint, safeIdentifier, sanitizeFolderKey, camelizeTag } from './helpers.js';
import { detectKeyCollisions } from './types.js';

const HEADER = `// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec> --client\n\nimport { z } from 'zod';\n\n`;

const OPTIONS_INTERFACE = `export interface ZwaggenClientOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  headers?:
    | Record<string, string>
    | (() => Record<string, string>)
    | (() => Promise<Record<string, string>>);
}`;

const ERROR_CLASS = `export class ZwaggenHttpError extends Error {
  constructor(public response: Response) {
    super(\`HTTP \${response.status} \${response.statusText}\`);
    this.name = 'ZwaggenHttpError';
  }
}`;

export function generateClient(spec: Spec): string {
  detectKeyCollisions(spec);
  const referencedTypes = collectReferencedTypeNames(spec);
  const importLine = referencedTypes.length > 0
    ? `import { ${referencedTypes.map((n) => `${n}Schema`).join(', ')} } from './schemas.js';\n`
    + `import type { ${referencedTypes.join(', ')} } from './types.js';\n\n`
    : '';

  const groups = groupByTag(spec.endpoints);
  const groupBlocks: string[] = [];
  for (const [tag, endpoints] of groups) {
    const methods = endpoints.map((e) => emitMethod(e, spec)).join(',\n');
    groupBlocks.push(`    ${safeIdentifier(camelizeTag(tag))}: {\n${methods},\n    }`);
  }

  return HEADER + importLine
    + OPTIONS_INTERFACE + '\n\n'
    + ERROR_CLASS + '\n\n'
    + `export function createClient(opts: ZwaggenClientOptions) {\n`
    + `  const f = opts.fetch ?? globalThis.fetch;\n`
    + `  const baseHeaders = async (): Promise<Record<string, string>> => {\n`
    + `    if (typeof opts.headers === 'function') return await opts.headers();\n`
    + `    return opts.headers ?? {};\n`
    + `  };\n`
    + `  return {\n${groupBlocks.join(',\n')},\n  };\n`
    + `}\n`;
}

/**
 * Dereferences array-alias type refs to their underlying array type so
 * response parsers can emit `z.array(XSchema).parse(...)` for list endpoints
 * that return a named alias like `UserList = User[]`. Object/union refs are
 * left as-is since they have a corresponding `${Name}Schema` to call directly.
 */
function dereferenceArrayAlias(def: TypeDef, spec: Spec): TypeDef {
  if (def.kind === 'ref') {
    const target = spec.types[def.ref];
    if (target && target.kind === 'array') return target;
  }
  return def;
}

function groupByTag(endpoints: Endpoint[]): Map<string, Endpoint[]> {
  const m = new Map<string, Endpoint[]>();
  for (const e of endpoints) {
    const tag = tagForEndpoint(e);
    if (!m.has(tag)) m.set(tag, []);
    m.get(tag)!.push(e);
  }
  return m;
}

function emitMethod(endpoint: Endpoint, spec: Spec): string {
  const methodName = methodNameFor(endpoint);
  const inputType = inputTypeFor(endpoint, spec);
  const ok = endpoint.responses.find((r) => r.status >= 200 && r.status < 300);
  const okType = ok ? dereferenceArrayAlias(ok.type, spec) : null;
  const returnType = okType ? tsRefType(okType, spec) : 'unknown';
  const parser = okType ? zodParseExpr(okType) : '';

  const urlExpr = buildUrlExpr(endpoint);
  const fetchOpts = buildFetchOptsExpr(endpoint);

  return `      async ${methodName}(${inputType ? `input: ${inputType}` : ''}): Promise<${returnType}> {\n`
    + `        const r = await f(${urlExpr}, ${fetchOpts});\n`
    + `        if (!r.ok) throw new ZwaggenHttpError(r);\n`
    + (parser ? `        return ${parser}(await r.json());\n` : `        return undefined as unknown as ${returnType};\n`)
    + `      }`;
}

function methodNameFor(endpoint: Endpoint): string {
  return safeIdentifier(camelize(endpoint.id));
}

function camelize(s: string): string {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase()).replace(/-/g, '');
}

function inputTypeFor(endpoint: Endpoint, spec: Spec): string {
  const parts: string[] = [];
  if (endpoint.pathParams.length > 0) {
    const fields = endpoint.pathParams.map((p) => `${safeIdentifier(p.name)}: ${tsRefType(p.type, spec)}`).join('; ');
    parts.push(`{ ${fields} }`);
  }
  if (endpoint.queryParams.length > 0) {
    const fields = endpoint.queryParams.map((p) => `${safeIdentifier(p.name)}${p.required ? '' : '?'}: ${tsRefType(p.type, spec)}`).join('; ');
    parts.push(`{ ${fields} }`);
  }
  if (endpoint.headers.length > 0) {
    const fields = endpoint.headers.map((p) => `${safeIdentifier(p.name)}${p.required ? '' : '?'}: ${tsRefType(p.type, spec)}`).join('; ');
    parts.push(`{ ${fields} }`);
  }
  const ct = endpoint.bodyContentType ?? 'json';
  if ((ct === 'urlencoded' || ct === 'multipart') && endpoint.bodyForm && endpoint.bodyForm.length > 0) {
    const fields = endpoint.bodyForm
      .map((p) => `${safeIdentifier(p.name)}${p.required ? '' : '?'}: ${tsRefType(p.type, spec)}`)
      .join('; ');
    parts.push(`{ body: { ${fields} } }`);
  } else if (ct === 'json' && endpoint.requestBody) {
    parts.push(`{ body: ${tsRefType(endpoint.requestBody, spec)} }`);
  }
  if (parts.length === 0) return '';
  return parts.join(' & ');
}

/**
 * Renders a TS type expression for use inline in client method signatures.
 * Differs from `types.ts:tsType` in that it doesn't emit interface/declaration
 * forms — just inline-shape strings (`{ x: string; y?: number }`, `User[]`,
 * etc.) that can sit in a parameter or return-type position.
 *
 * Inline `kind: 'object'` is recursively expanded into a real shape rather
 * than collapsing to `unknown`, so codegen of OpenAPI specs (which often
 * inline request bodies) produces useful types instead of opaque inputs.
 * Refs still resolve to their sanitized folder-key name.
 */
function tsRefType(def: TypeDef, spec: Spec): string {
  switch (def.kind) {
    case 'string': return 'string';
    case 'number':
    case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'null': return 'null';
    case 'literal': return typeof def.value === 'string' ? `'${def.value}'` : String(def.value);
    case 'array': return `${tsRefType(def.element, spec)}[]`;
    case 'union': return def.variants.map((v) => tsRefType(v, spec)).join(' | ');
    case 'ref': return sanitizeFolderKey(def.ref);
    case 'object': {
      if (def.fields.length === 0) return '{}';
      const fields = def.fields
        .map((f) => {
          const opt = f.required ? '' : '?';
          return `${safeIdentifier(f.name)}${opt}: ${tsRefType(f.type, spec)}`;
        })
        .join('; ');
      return `{ ${fields} }`;
    }
  }
}

function zodParseExpr(def: TypeDef): string {
  switch (def.kind) {
    case 'ref': return `${sanitizeFolderKey(def.ref)}Schema.parse`;
    case 'array': {
      if (def.element.kind === 'ref') return `z.array(${sanitizeFolderKey(def.element.ref)}Schema).parse`;
      return `z.array(${zodTypeExpr(def.element)}).parse`;
    }
    default: return `${zodTypeExpr(def)}.parse`;
  }
}

function zodTypeExpr(def: TypeDef): string {
  switch (def.kind) {
    case 'string': return 'z.string()';
    case 'number':
    case 'integer': return 'z.number()';
    case 'boolean': return 'z.boolean()';
    case 'ref': return `${sanitizeFolderKey(def.ref)}Schema`;
    case 'array': return `z.array(${zodTypeExpr(def.element)})`;
    default: return 'z.unknown()';
  }
}

function buildUrlExpr(endpoint: Endpoint): string {
  const path = endpoint.path.replace(/\{([^}]+)\}/g, (_, name) => `\${encodeURIComponent(input[${JSON.stringify(name)}])}`);
  if (endpoint.queryParams.length === 0) {
    return `\`\${opts.baseUrl}${path}\``;
  }
  // Build query string from non-undefined values only.
  const qsLines = endpoint.queryParams.map((p) => {
    const access = `input[${JSON.stringify(p.name)}]`;
    return `if (${access} !== undefined) qs.set(${JSON.stringify(p.name)}, String(${access}));`;
  }).join('\n          ');
  return `(() => {\n          const qs = new URLSearchParams();\n          ${qsLines}\n          const q = qs.toString();\n          return \`\${opts.baseUrl}${path}\${q ? '?' + q : ''}\`;\n        })()`;
}

function quoteHeaderName(name: string): string {
  // HTTP headers usually contain '-', so quote them. Use JSON.stringify for safety.
  return JSON.stringify(name);
}

function buildFetchOptsExpr(endpoint: Endpoint): string {
  const ct = endpoint.bodyContentType ?? 'json';
  const hasFormBody = (ct === 'urlencoded' || ct === 'multipart') && (endpoint.bodyForm?.length ?? 0) > 0;
  const hasJsonBody = ct === 'json' && !!endpoint.requestBody;
  const hasBody = hasJsonBody || hasFormBody;

  const headerSpread = endpoint.headers.length > 0
    ? `, ${endpoint.headers.map((p) => `${quoteHeaderName(p.name)}: input[${JSON.stringify(p.name)}]`).join(', ')}`
    : '';

  const contentTypeKV =
    hasJsonBody ? `'content-type': 'application/json', ` :
    ct === 'urlencoded' && hasFormBody ? `'content-type': 'application/x-www-form-urlencoded', ` :
    '';
  const baseHeaderObj = hasBody
    ? `{ ${contentTypeKV}...(await baseHeaders())${headerSpread} }`
    : `{ ...(await baseHeaders())${headerSpread} }`;

  // For GET/HEAD with no per-endpoint headers, keep the simpler `await baseHeaders()` shape.
  const headersExpr = endpoint.headers.length === 0 && !hasBody
    ? '(await baseHeaders())'
    : baseHeaderObj;

  const method = endpoint.method;
  if (method === 'GET' || method === 'HEAD') {
    return `{ method: '${method}', headers: ${headersExpr} }`;
  }
  if (ct === 'urlencoded' && hasFormBody) {
    return `{ method: '${method}', headers: ${headersExpr}, body: new URLSearchParams(input.body as Record<string, string>).toString() }`;
  }
  if (ct === 'multipart' && hasFormBody) {
    // Multipart codegen lands in v1.2 (needs File support and FormData
    // construction). Throw at runtime so the typed shape still compiles but
    // misuse fails loudly with a clear message.
    return `(() => { throw new Error('Codegen: multipart bodies are not yet supported. Use the playground or open an issue.'); })()`;
  }
  if (hasJsonBody) {
    return `{ method: '${method}', headers: ${headersExpr}, body: JSON.stringify(input.body) }`;
  }
  return `{ method: '${method}', headers: ${headersExpr} }`;
}

function collectReferencedTypeNames(spec: Spec): string[] {
  const set = new Set<string>();
  const walk = (def: TypeDef): void => {
    switch (def.kind) {
      case 'ref': set.add(sanitizeFolderKey(def.ref)); break;
      case 'array': walk(def.element); break;
      case 'union': def.variants.forEach(walk); break;
      case 'object': def.fields.forEach((f) => walk(f.type)); break;
    }
  };
  for (const e of spec.endpoints) {
    if (e.requestBody) walk(e.requestBody);
    e.bodyForm?.forEach((p) => walk(p.type));
    e.responses.forEach((r: ResponseDef) => walk(dereferenceArrayAlias(r.type, spec)));
    e.pathParams.forEach((p) => walk(p.type));
    e.queryParams.forEach((p) => walk(p.type));
    e.headers.forEach((p) => walk(p.type));
  }
  return [...set].sort();
}
