import { resolveParamFields, findIllegalFileTypes, type Spec, type Endpoint, type TypeDef, type ResponseDef } from '@zwaggen/core';
import { tagForEndpoint, safeIdentifier, sanitizeFolderKey, camelizeTag } from './helpers.js';
import { detectKeyCollisions } from './types.js';

// File requires Node 20+ at runtime; modern browsers, Bun, and Deno also ship
// it. Mention this once in the generated header so the universal-runtime
// promise stays honest for multipart endpoints.
const HEADER = `// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec> --client\n// Multipart endpoints rely on globalThis.File (Node 20+, modern browsers, Bun, Deno).\n\nimport { z } from 'zod';\n\n`;

const OPTIONS_INTERFACE = `export interface ZwaggenClientOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  headers?:
    | Record<string, string>
    | (() => Record<string, string>)
    | (() => Promise<Record<string, string>>);
}`;

const ERROR_CLASS = `export class ZwaggenHttpError extends Error {
  constructor(public response: Response) {
    super(\`HTTP \${response.status} \${response.statusText}\`);
    this.name = 'ZwaggenHttpError';
  }
}`;

/**
 * Aborts generation if the Spec contains any illegally-placed `'file'`
 * TypeDef. Surfaced for both the client + types/zod generators so the failure
 * mode is identical regardless of which artifact triggered the run.
 */
function assertNoIllegalFileTypes(spec: Spec): void {
  const errs = findIllegalFileTypes(spec);
  if (errs.length === 0) return;
  throw new Error(
    'Codegen aborted — illegal file type placements:\n' +
      errs.map((e) => `  • ${e.where}: ${e.message}`).join('\n'),
  );
}

export function generateClient(spec: Spec): string {
  assertNoIllegalFileTypes(spec);
  detectKeyCollisions(spec);
  const referencedTypes = collectReferencedTypeNames(spec);
  const importLine = referencedTypes.length > 0
    ? `import { ${referencedTypes.map((n) => `${n}Schema`).join(', ')} } from './schemas.js';\n`
    + `import type { ${referencedTypes.join(', ')} } from './types.js';\n\n`
    : '';

  const groups = groupByTag(spec.endpoints);
  const groupBlocks: string[] = [];
  for (const [tag, endpoints] of groups) {
    const methods = endpoints.map((e) => emitMethod(e, spec)).join(',\n');
    groupBlocks.push(`    ${safeIdentifier(camelizeTag(tag))}: {\n${methods},\n    }`);
  }

  return HEADER + importLine
    + OPTIONS_INTERFACE + '\n\n'
    + ERROR_CLASS + '\n\n'
    + `export function createClient(opts: ZwaggenClientOptions) {\n`
    + `  const f = opts.fetch ?? globalThis.fetch;\n`
    + `  const baseHeaders = async (): Promise<Record<string, string>> => {\n`
    + `    if (typeof opts.headers === 'function') return await opts.headers();\n`
    + `    return opts.headers ?? {};\n`
    + `  };\n`
    + `  return {\n${groupBlocks.join(',\n')},\n  };\n`
    + `}\n`;
}

/**
 * Dereferences array-alias type refs to their underlying array type so
 * response parsers can emit `z.array(XSchema).parse(...)` for list endpoints
 * that return a named alias like `UserList = User[]`. Object/union refs are
 * left as-is since they have a corresponding `${Name}Schema` to call directly.
 */
function dereferenceArrayAlias(def: TypeDef, spec: Spec): TypeDef {
  if (def.kind === 'ref') {
    const target = spec.types[def.ref];
    if (target && target.kind === 'array') return target;
  }
  return def;
}

function groupByTag(endpoints: Endpoint[]): Map<string, Endpoint[]> {
  const m = new Map<string, Endpoint[]>();
  for (const e of endpoints) {
    const tag = tagForEndpoint(e);
    if (!m.has(tag)) m.set(tag, []);
    m.get(tag)!.push(e);
  }
  return m;
}

function emitMethod(endpoint: Endpoint, spec: Spec): string {
  const methodName = methodNameFor(endpoint);
  const inputType = inputTypeFor(endpoint, spec);
  const ok = endpoint.responses.find((r) => r.status >= 200 && r.status < 300);
  const okType = ok ? dereferenceArrayAlias(ok.type, spec) : null;
  const returnType = okType ? tsRefType(okType, spec) : 'unknown';
  const parser = okType ? zodParseExpr(okType) : '';

  const urlExpr = buildUrlExpr(endpoint, spec);
  const fetchOpts = buildFetchOptsExpr(endpoint, spec);

  return `      async ${methodName}(${inputType ? `input: ${inputType}` : ''}): Promise<${returnType}> {\n`
    + `        const r = await f(${urlExpr}, ${fetchOpts});\n`
    + `        if (!r.ok) throw new ZwaggenHttpError(r);\n`
    + (parser ? `        return ${parser}(await r.json());\n` : `        return undefined as unknown as ${returnType};\n`)
    + `      }`;
}

function methodNameFor(endpoint: Endpoint): string {
  return safeIdentifier(camelize(endpoint.id));
}

function camelize(s: string): string {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase()).replace(/-/g, '');
}

function inputTypeFor(endpoint: Endpoint, spec: Spec): string {
  const parts: string[] = [];
  if (endpoint.pathParams.length > 0) {
    const fields = endpoint.pathParams.map((p) => `${safeIdentifier(p.name)}: ${tsRefType(p.type, spec)}`).join('; ');
    parts.push(`{ ${fields} }`);
  }
  const queryFields = resolveParamFields(endpoint.queryParams, spec);
  if (queryFields.length > 0) {
    const fields = queryFields.map((p) => `${safeIdentifier(p.name)}${p.required ? '' : '?'}: ${tsRefType(p.type, spec)}`).join('; ');
    parts.push(`{ ${fields} }`);
  }
  const headerFields = resolveParamFields(endpoint.headers, spec);
  if (headerFields.length > 0) {
    const fields = headerFields.map((p) => `${safeIdentifier(p.name)}${p.required ? '' : '?'}: ${tsRefType(p.type, spec)}`).join('; ');
    parts.push(`{ ${fields} }`);
  }
  const ct = endpoint.bodyContentType ?? 'json';
  if ((ct === 'urlencoded' || ct === 'multipart') && endpoint.bodyForm && endpoint.bodyForm.length > 0) {
    const fields = endpoint.bodyForm
      .map((p) => `${safeIdentifier(p.name)}${p.required ? '' : '?'}: ${tsRefType(p.type, spec)}`)
      .join('; ');
    parts.push(`{ body: { ${fields} } }`);
  } else if (ct === 'json' && endpoint.requestBody) {
    parts.push(`{ body: ${tsRefType(endpoint.requestBody, spec)} }`);
  }
  if (parts.length === 0) return '';
  return parts.join(' & ');
}

/**
 * Renders a TS type expression for use inline in client method signatures.
 * Differs from `types.ts:tsType` in that it doesn't emit interface/declaration
 * forms — just inline-shape strings (`{ x: string; y?: number }`, `User[]`,
 * etc.) that can sit in a parameter or return-type position.
 *
 * Inline `kind: 'object'` is recursively expanded into a real shape rather
 * than collapsing to `unknown`, so codegen of OpenAPI specs (which often
 * inline request bodies) produces useful types instead of opaque inputs.
 * Refs still resolve to their sanitized folder-key name.
 */
function tsRefType(def: TypeDef, spec: Spec): string {
  switch (def.kind) {
    case 'string': return 'string';
    case 'number':
    case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'null': return 'null';
    case 'literal': return typeof def.value === 'string' ? `'${def.value}'` : String(def.value);
    case 'array': return `${tsRefType(def.element, spec)}[]`;
    case 'union': return def.variants.map((v) => tsRefType(v, spec)).join(' | ');
    case 'ref': return sanitizeFolderKey(def.ref);
    case 'file': return 'File';
    case 'object': {
      if (def.fields.length === 0) return '{}';
      const fields = def.fields
        .map((f) => {
          const opt = f.required ? '' : '?';
          return `${safeIdentifier(f.name)}${opt}: ${tsRefType(f.type, spec)}`;
        })
        .join('; ');
      return `{ ${fields} }`;
    }
  }
}

function zodParseExpr(def: TypeDef): string {
  switch (def.kind) {
    case 'ref': return `${sanitizeFolderKey(def.ref)}Schema.parse`;
    case 'array': {
      if (def.element.kind === 'ref') return `z.array(${sanitizeFolderKey(def.element.ref)}Schema).parse`;
      return `z.array(${zodTypeExpr(def.element)}).parse`;
    }
    default: return `${zodTypeExpr(def)}.parse`;
  }
}

function zodTypeExpr(def: TypeDef): string {
  switch (def.kind) {
    case 'string': return 'z.string()';
    case 'number':
    case 'integer': return 'z.number()';
    case 'boolean': return 'z.boolean()';
    case 'ref': return `${sanitizeFolderKey(def.ref)}Schema`;
    case 'array': return `z.array(${zodTypeExpr(def.element)})`;
    // Mirror of tsRefType's object-case expansion (v1.2). Inline-object
    // response shapes — common after OpenAPI import — now generate a real
    // z.object({...}) instead of collapsing to z.unknown(). Empty objects
    // emit z.object({}) for parity with the TS side's `{}`.
    case 'object': {
      if (def.fields.length === 0) return 'z.object({})';
      const fields = def.fields.map((f) => {
        const inner = zodTypeExpr(f.type);
        const tail = f.required ? '' : '.optional()';
        return `${JSON.stringify(f.name)}: ${inner}${tail}`;
      }).join(', ');
      return `z.object({ ${fields} })`;
    }
    // File never appears in responses — the validator rejects file types
    // outside of multipart bodyForm. Mirror as z.instanceof(File) for safety
    // if the unreachable branch is somehow hit.
    case 'file': return 'z.instanceof(File)';
    default: return 'z.unknown()';
  }
}

function buildUrlExpr(endpoint: Endpoint, spec: Spec): string {
  const path = endpoint.path.replace(/\{([^}]+)\}/g, (_, name) => `\${encodeURIComponent(input[${JSON.stringify(name)}])}`);
  const expandedQuery = resolveParamFields(endpoint.queryParams, spec);
  if (expandedQuery.length === 0) {
    return `\`\${opts.baseUrl}${path}\``;
  }
  // Build query string from non-undefined values only.
  const qsLines = expandedQuery.map((p) => {
    const access = `input[${JSON.stringify(p.name)}]`;
    return `if (${access} !== undefined) qs.set(${JSON.stringify(p.name)}, String(${access}));`;
  }).join('\n          ');
  return `(() => {\n          const qs = new URLSearchParams();\n          ${qsLines}\n          const q = qs.toString();\n          return \`\${opts.baseUrl}${path}\${q ? '?' + q : ''}\`;\n        })()`;
}

function quoteHeaderName(name: string): string {
  // HTTP headers usually contain '-', so quote them. Use JSON.stringify for safety.
  return JSON.stringify(name);
}

function buildFetchOptsExpr(endpoint: Endpoint, spec: Spec): string {
  const ct = endpoint.bodyContentType ?? 'json';
  const hasFormBody = (ct === 'urlencoded' || ct === 'multipart') && (endpoint.bodyForm?.length ?? 0) > 0;
  const hasJsonBody = ct === 'json' && !!endpoint.requestBody;
  const hasBody = hasJsonBody || hasFormBody;

  const expandedHeaders = resolveParamFields(endpoint.headers, spec);
  const headerSpread = expandedHeaders.length > 0
    ? `, ${expandedHeaders.map((p) => `${quoteHeaderName(p.name)}: input[${JSON.stringify(p.name)}]`).join(', ')}`
    : '';

  const contentTypeKV =
    hasJsonBody ? `'content-type': 'application/json', ` :
    ct === 'urlencoded' && hasFormBody ? `'content-type': 'application/x-www-form-urlencoded', ` :
    '';
  const baseHeaderObj = hasBody
    ? `{ ${contentTypeKV}...(await baseHeaders())${headerSpread} }`
    : `{ ...(await baseHeaders())${headerSpread} }`;

  // For GET/HEAD with no per-endpoint headers, keep the simpler `await baseHeaders()` shape.
  const headersExpr = expandedHeaders.length === 0 && !hasBody
    ? '(await baseHeaders())'
    : baseHeaderObj;

  const method = endpoint.method;
  if (method === 'GET' || method === 'HEAD') {
    return `{ method: '${method}', headers: ${headersExpr} }`;
  }
  if (ct === 'urlencoded' && hasFormBody) {
    return `{ method: '${method}', headers: ${headersExpr}, body: new URLSearchParams(input.body as Record<string, string>).toString() }`;
  }
  if (ct === 'multipart' && hasFormBody) {
    return `{ method: '${method}', headers: ${headersExpr}, body: ${buildMultipartBodyExpr(endpoint)} }`;
  }
  if (hasJsonBody) {
    return `{ method: '${method}', headers: ${headersExpr}, body: JSON.stringify(input.body) }`;
  }
  return `{ method: '${method}', headers: ${headersExpr} }`;
}

/**
 * Emits an inline IIFE that constructs a FormData from the endpoint's
 * `bodyForm` fields. File-typed fields use `fd.append(name, value, value.name)`
 * to preserve the filename; everything else stringifies. Optional fields
 * skip the append when undefined. Returns a single expression so it can be
 * dropped into a `body: ...` slot.
 */
function buildMultipartBodyExpr(endpoint: Endpoint): string {
  const fields = endpoint.bodyForm ?? [];
  const lines = fields.map((p) => {
    const access = `input.body[${JSON.stringify(p.name)}]`;
    const append = p.type.kind === 'file'
      ? `fd.append(${JSON.stringify(p.name)}, ${access} as File, (${access} as File).name);`
      : `fd.append(${JSON.stringify(p.name)}, String(${access}));`;
    return p.required ? append : `if (${access} !== undefined) ${append}`;
  });
  return `(() => { const fd = new FormData(); ${lines.join(' ')} return fd; })()`;
}

function collectReferencedTypeNames(spec: Spec): string[] {
  const set = new Set<string>();
  const walk = (def: TypeDef): void => {
    switch (def.kind) {
      case 'ref': set.add(sanitizeFolderKey(def.ref)); break;
      case 'array': walk(def.element); break;
      case 'union': def.variants.forEach(walk); break;
      case 'object': def.fields.forEach((f) => walk(f.type)); break;
    }
  };
  for (const e of spec.endpoints) {
    if (e.requestBody) walk(e.requestBody);
    e.bodyForm?.forEach((p) => walk(p.type));
    e.responses.forEach((r: ResponseDef) => walk(dereferenceArrayAlias(r.type, spec)));
    e.pathParams.forEach((p) => walk(p.type));
    // v7: queryParams/headers are ObjectType | RefType | undefined. RefType
    // is reachable through the named-types walk above; for inline objects
    // we walk each field's type directly. Both cases pass through walk()
    // which records ref names into `set`.
    if (e.queryParams) walk(e.queryParams);
    if (e.headers) walk(e.headers);
  }
  return [...set].sort();
}
