import type { Spec, Endpoint, TypeDef, ResponseDef } from '@zwaggen/core';
import { tagForEndpoint, safeIdentifier } from './helpers.js';

const HEADER = `// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec> --client\n\nimport { z } from 'zod';\n\n`;

const OPTIONS_INTERFACE = `export interface ZwaggenClientOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  headers?: Record<string, string> | (() => Record<string, string>);
}`;

const ERROR_CLASS = `export class ZwaggenHttpError extends Error {
  constructor(public response: Response) {
    super(\`HTTP \${response.status} \${response.statusText}\`);
    this.name = 'ZwaggenHttpError';
  }
}`;

export function generateClient(spec: Spec): string {
  const referencedTypes = collectReferencedTypeNames(spec);
  const importLine = referencedTypes.length > 0
    ? `import { ${referencedTypes.map((n) => `${n}Schema`).join(', ')} } from './schemas.js';\n`
    + `import type { ${referencedTypes.join(', ')} } from './types.js';\n\n`
    : '';

  const groups = groupByTag(spec.endpoints);
  const groupBlocks: string[] = [];
  for (const [tag, endpoints] of groups) {
    const methods = endpoints.map((e) => emitMethod(e, spec)).join(',\n');
    groupBlocks.push(`    ${safeIdentifier(tag)}: {\n${methods},\n    }`);
  }

  return HEADER + importLine
    + OPTIONS_INTERFACE + '\n\n'
    + ERROR_CLASS + '\n\n'
    + `export function createClient(opts: ZwaggenClientOptions) {\n`
    + `  const f = opts.fetch ?? globalThis.fetch;\n`
    + `  const baseHeaders = () => typeof opts.headers === 'function' ? opts.headers() : (opts.headers ?? {});\n`
    + `  return {\n${groupBlocks.join(',\n')},\n  };\n`
    + `}\n`;
}

/**
 * Dereferences array-alias type refs to their underlying array type so
 * response parsers can emit `z.array(XSchema).parse(...)` for list endpoints
 * that return a named alias like `UserList = User[]`. Object/union refs are
 * left as-is since they have a corresponding `${Name}Schema` to call directly.
 */
function dereferenceArrayAlias(def: TypeDef, spec: Spec): TypeDef {
  if (def.kind === 'ref') {
    const target = spec.types[def.ref];
    if (target && target.kind === 'array') return target;
  }
  return def;
}

function groupByTag(endpoints: Endpoint[]): Map<string, Endpoint[]> {
  const m = new Map<string, Endpoint[]>();
  for (const e of endpoints) {
    const tag = tagForEndpoint(e);
    if (!m.has(tag)) m.set(tag, []);
    m.get(tag)!.push(e);
  }
  return m;
}

function emitMethod(endpoint: Endpoint, spec: Spec): string {
  const methodName = methodNameFor(endpoint);
  const inputType = inputTypeFor(endpoint);
  const ok = endpoint.responses.find((r) => r.status >= 200 && r.status < 300);
  const okType = ok ? dereferenceArrayAlias(ok.type, spec) : null;
  const returnType = okType ? tsRefType(okType) : 'unknown';
  const parser = okType ? zodParseExpr(okType) : '';

  const urlExpr = buildUrlExpr(endpoint);
  const fetchOpts = buildFetchOptsExpr(endpoint);

  return `      async ${methodName}(${inputType ? `input: ${inputType}` : ''}): Promise<${returnType}> {\n`
    + `        const r = await f(${urlExpr}, ${fetchOpts});\n`
    + `        if (!r.ok) throw new ZwaggenHttpError(r);\n`
    + (parser ? `        return ${parser}(await r.json());\n` : `        return undefined as unknown as ${returnType};\n`)
    + `      }`;
}

function methodNameFor(endpoint: Endpoint): string {
  return safeIdentifier(camelize(endpoint.id));
}

function camelize(s: string): string {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase()).replace(/-/g, '');
}

function inputTypeFor(endpoint: Endpoint): string {
  const parts: string[] = [];
  if (endpoint.pathParams.length > 0) {
    const fields = endpoint.pathParams.map((p) => `${safeIdentifier(p.name)}: ${tsRefType(p.type)}`).join('; ');
    parts.push(`{ ${fields} }`);
  }
  if (endpoint.queryParams.length > 0) {
    const fields = endpoint.queryParams.map((p) => `${safeIdentifier(p.name)}${p.required ? '' : '?'}: ${tsRefType(p.type)}`).join('; ');
    parts.push(`{ ${fields} }`);
  }
  if (endpoint.headers.length > 0) {
    const fields = endpoint.headers.map((p) => `${safeIdentifier(p.name)}${p.required ? '' : '?'}: ${tsRefType(p.type)}`).join('; ');
    parts.push(`{ ${fields} }`);
  }
  if (endpoint.requestBody) {
    parts.push(`{ body: ${tsRefType(endpoint.requestBody)} }`);
  }
  if (parts.length === 0) return '';
  return parts.join(' & ');
}

function tsRefType(def: TypeDef): string {
  switch (def.kind) {
    case 'string': return 'string';
    case 'number':
    case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'null': return 'null';
    case 'literal': return typeof def.value === 'string' ? `'${def.value}'` : String(def.value);
    case 'array': return `${tsRefType(def.element)}[]`;
    case 'union': return def.variants.map(tsRefType).join(' | ');
    case 'ref': return def.ref;
    case 'object': return 'unknown';
  }
}

function zodParseExpr(def: TypeDef): string {
  switch (def.kind) {
    case 'ref': return `${def.ref}Schema.parse`;
    case 'array': {
      if (def.element.kind === 'ref') return `z.array(${def.element.ref}Schema).parse`;
      return `z.array(${zodTypeExpr(def.element)}).parse`;
    }
    default: return `${zodTypeExpr(def)}.parse`;
  }
}

function zodTypeExpr(def: TypeDef): string {
  switch (def.kind) {
    case 'string': return 'z.string()';
    case 'number':
    case 'integer': return 'z.number()';
    case 'boolean': return 'z.boolean()';
    case 'ref': return `${def.ref}Schema`;
    case 'array': return `z.array(${zodTypeExpr(def.element)})`;
    default: return 'z.unknown()';
  }
}

function buildUrlExpr(endpoint: Endpoint): string {
  const path = endpoint.path.replace(/\{([^}]+)\}/g, (_, name) => `\${encodeURIComponent(input[${JSON.stringify(name)}])}`);
  if (endpoint.queryParams.length === 0) {
    return `\`\${opts.baseUrl}${path}\``;
  }
  // Build query string from non-undefined values only.
  const qsLines = endpoint.queryParams.map((p) => {
    const access = `input[${JSON.stringify(p.name)}]`;
    return `if (${access} !== undefined) qs.set(${JSON.stringify(p.name)}, String(${access}));`;
  }).join('\n          ');
  return `(() => {\n          const qs = new URLSearchParams();\n          ${qsLines}\n          const q = qs.toString();\n          return \`\${opts.baseUrl}${path}\${q ? '?' + q : ''}\`;\n        })()`;
}

function quoteHeaderName(name: string): string {
  // HTTP headers usually contain '-', so quote them. Use JSON.stringify for safety.
  return JSON.stringify(name);
}

function buildFetchOptsExpr(endpoint: Endpoint): string {
  const headerSpread = endpoint.headers.length > 0
    ? `, ${endpoint.headers.map((p) => `${quoteHeaderName(p.name)}: input[${JSON.stringify(p.name)}]`).join(', ')}`
    : '';
  const baseHeaderObj = endpoint.requestBody
    ? `{ 'content-type': 'application/json', ...baseHeaders()${headerSpread} }`
    : `{ ...baseHeaders()${headerSpread} }`;

  // For GET/HEAD with no per-endpoint headers, keep the simpler `baseHeaders()` shape.
  const headersExpr = endpoint.headers.length === 0 && !endpoint.requestBody
    ? 'baseHeaders()'
    : baseHeaderObj;

  const method = endpoint.method;
  if (method === 'GET' || method === 'HEAD') {
    return `{ method: '${method}', headers: ${headersExpr} }`;
  }
  if (endpoint.requestBody) {
    return `{ method: '${method}', headers: ${headersExpr}, body: JSON.stringify(input.body) }`;
  }
  return `{ method: '${method}', headers: ${headersExpr} }`;
}

function collectReferencedTypeNames(spec: Spec): string[] {
  const set = new Set<string>();
  const walk = (def: TypeDef): void => {
    switch (def.kind) {
      case 'ref': set.add(def.ref); break;
      case 'array': walk(def.element); break;
      case 'union': def.variants.forEach(walk); break;
      case 'object': def.fields.forEach((f) => walk(f.type)); break;
    }
  };
  for (const e of spec.endpoints) {
    if (e.requestBody) walk(e.requestBody);
    e.responses.forEach((r: ResponseDef) => walk(dereferenceArrayAlias(r.type, spec)));
    e.pathParams.forEach((p) => walk(p.type));
    e.queryParams.forEach((p) => walk(p.type));
    e.headers.forEach((p) => walk(p.type));
  }
  return [...set].sort();
}
