import type {
  Spec,
  TypeDef,
  ObjectType,
  ObjectField,
  ArrayType,
  LiteralType,
} from '@zwaggen/core';
import { safeIdentifier } from './helpers.js';

const HEADER = `// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec>\n\n`;

export function generateTs(spec: Spec): string {
  const lines: string[] = [HEADER];
  for (const [name, def] of Object.entries(spec.types)) {
    lines.push(emitTopLevel(name, def, spec));
    lines.push('');
  }
  return lines.join('\n');
}

function emitTopLevel(name: string, def: TypeDef, spec: Spec): string {
  if (def.kind === 'object') return emitInterface(name, def, spec);
  return `export type ${name} = ${tsType(def, spec)};`;
}

function emitInterface(name: string, def: ObjectType, spec: Spec): string {
  const head =
    def.extends && def.extends.length > 0
      ? `export interface ${name} extends ${def.extends.join(', ')} {`
      : `export interface ${name} {`;
  const body = def.fields.map((f) => emitField(f, spec)).join('\n');
  return body ? `${head}\n${body}\n}` : `${head}}`;
}

function emitField(field: ObjectField, spec: Spec): string {
  const key = safeIdentifier(field.name);
  const optional = field.required ? '' : '?';
  return `  ${key}${optional}: ${tsType(field.type, spec)};`;
}

function tsType(def: TypeDef, spec: Spec): string {
  switch (def.kind) {
    case 'string':
      return 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    case 'literal':
      return literalToTs(def);
    case 'array':
      return `${arrayItem(def, spec)}[]`;
    case 'union':
      return def.variants.map((v) => tsType(v, spec)).join(' | ');
    case 'ref':
      return def.ref;
    case 'object': {
      const fields = def.fields.map((f) => emitField(f, spec)).join('\n');
      return fields ? `{\n${fields}\n}` : '{}';
    }
  }
}

function arrayItem(def: ArrayType, spec: Spec): string {
  const t = tsType(def.element, spec);
  return def.element.kind === 'union' ? `(${t})` : t;
}

function literalToTs(def: LiteralType): string {
  if (typeof def.value === 'string') return `'${def.value.replace(/'/g, "\\'")}'`;
  if (typeof def.value === 'number') return String(def.value);
  if (typeof def.value === 'boolean') return String(def.value);
  if (def.value === null) return 'null';
  return JSON.stringify(def.value);
}
