import {
  findIllegalFileTypes,
  type Spec,
  type TypeDef,
  type ObjectType,
  type ObjectField,
  type ArrayType,
  type LiteralType,
} from '@zwaggen/core';
import { safeIdentifier, sanitizeFolderKey } from '@zwaggen/core';

const HEADER = `// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec>\n\n`;

/**
 * Throws if two distinct spec type keys sanitize to the same emitted name
 * (e.g. `auth/User` and `auth_User` both → `auth_User`). This is rare but
 * silently overwriting one with the other would be worse than failing fast.
 */
export function detectKeyCollisions(spec: Spec): void {
  const seen = new Map<string, string>();
  for (const key of Object.keys(spec.types)) {
    const s = sanitizeFolderKey(key);
    const prior = seen.get(s);
    if (prior !== undefined && prior !== key) {
      throw new Error(
        `Codegen key collision: "${prior}" and "${key}" both sanitize to "${s}". Rename one.`,
      );
    }
    seen.set(s, key);
  }
}

/**
 * Aborts if the Spec contains any illegally-placed `'file'` TypeDef. Mirrors
 * the same gate used by `generateClient`/`generateZod` so users see a single
 * consistent failure message regardless of artifact.
 */
function assertNoIllegalFileTypesForTypes(spec: Spec): void {
  const errs = findIllegalFileTypes(spec);
  if (errs.length === 0) return;
  throw new Error(
    'Codegen aborted — illegal file type placements:\n' +
      errs.map((e) => `  • ${e.where}: ${e.message}`).join('\n'),
  );
}

export function generateTs(spec: Spec): string {
  assertNoIllegalFileTypesForTypes(spec);
  detectKeyCollisions(spec);
  const lines: string[] = [HEADER];
  for (const [name, def] of Object.entries(spec.types)) {
    lines.push(emitTopLevel(sanitizeFolderKey(name), def, spec));
    lines.push('');
  }
  return lines.join('\n');
}

function emitTopLevel(name: string, def: TypeDef, spec: Spec): string {
  if (def.kind === 'object') return emitInterface(name, def, spec);
  return `export type ${name} = ${tsType(def, spec)};`;
}

function emitInterface(name: string, def: ObjectType, spec: Spec): string {
  const head =
    def.extends && def.extends.length > 0
      ? `export interface ${name} extends ${def.extends.map(sanitizeFolderKey).join(', ')} {`
      : `export interface ${name} {`;
  const body = def.fields.map((f) => emitField(f, spec)).join('\n');
  return body ? `${head}\n${body}\n}` : `${head}}`;
}

function emitField(field: ObjectField, spec: Spec): string {
  const key = safeIdentifier(field.name);
  const optional = field.required ? '' : '?';
  return `  ${key}${optional}: ${tsType(field.type, spec)};`;
}

function tsType(def: TypeDef, spec: Spec): string {
  switch (def.kind) {
    case 'string':
      return 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    case 'literal':
      return literalToTs(def);
    case 'array':
      return `${arrayItem(def, spec)}[]`;
    case 'union':
      return def.variants.map((v) => tsType(v, spec)).join(' | ');
    case 'ref':
      return sanitizeFolderKey(def.ref);
    case 'file':
      // The validator should reject all FileType placements before reaching
      // the types emitter; this branch exists so the switch stays exhaustive.
      return 'File';
    case 'object': {
      const fields = def.fields.map((f) => emitField(f, spec)).join('\n');
      return fields ? `{\n${fields}\n}` : '{}';
    }
  }
}

function arrayItem(def: ArrayType, spec: Spec): string {
  const t = tsType(def.element, spec);
  return def.element.kind === 'union' ? `(${t})` : t;
}

function literalToTs(def: LiteralType): string {
  if (typeof def.value === 'string') return `'${def.value.replace(/'/g, "\\'")}'`;
  if (typeof def.value === 'number') return String(def.value);
  if (typeof def.value === 'boolean') return String(def.value);
  if (def.value === null) return 'null';
  return JSON.stringify(def.value);
}
