// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec>

export interface auth_User {
  id: string;
  email: string;
}

export interface billing_Invoice {
  amount: number;
}

export type Status = 'active' | 'archived';
