// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec>

import { z } from 'zod';

export const UserSchema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string().optional(),
  age: z.number().int().optional(),
});
export type User = z.infer<typeof UserSchema>;

export const AdminSchema = UserSchema.extend({
  role: z.enum(['admin', 'super-admin']),
});
export type Admin = z.infer<typeof AdminSchema>;

export const UserListSchema = z.array(UserSchema);
export type UserList = z.infer<typeof UserListSchema>;

export const StatusSchema = z.enum(['active', 'archived']);
export type Status = z.infer<typeof StatusSchema>;
