// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec> --client

import { z } from 'zod';

import { UserSchema } from './schemas.js';
import type { User } from './types.js';

export interface ZwaggenClientOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  headers?: Record<string, string> | (() => Record<string, string>);
}

export class ZwaggenHttpError extends Error {
  constructor(public response: Response) {
    super(`HTTP ${response.status} ${response.statusText}`);
    this.name = 'ZwaggenHttpError';
  }
}

export function createClient(opts: ZwaggenClientOptions) {
  const f = opts.fetch ?? globalThis.fetch;
  const baseHeaders = () =>
    typeof opts.headers === 'function' ? opts.headers() : (opts.headers ?? {});
  return {
    users: {
      async listUsers(): Promise<User[]> {
        const r = await f(`${opts.baseUrl}/users`, { method: 'GET', headers: baseHeaders() });
        if (!r.ok) throw new ZwaggenHttpError(r);
        return z.array(UserSchema).parse(await r.json());
      },
      async getUser(input: { id: string }): Promise<User> {
        const r = await f(`${opts.baseUrl}/users/${input.id}`, {
          method: 'GET',
          headers: baseHeaders(),
        });
        if (!r.ok) throw new ZwaggenHttpError(r);
        return UserSchema.parse(await r.json());
      },
      async createUser(input: { body: User }): Promise<User> {
        const r = await f(`${opts.baseUrl}/users`, {
          method: 'POST',
          headers: { 'content-type': 'application/json', ...baseHeaders() },
          body: JSON.stringify(input.body),
        });
        if (!r.ok) throw new ZwaggenHttpError(r);
        return UserSchema.parse(await r.json());
      },
    },
  };
}
