// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec>

export interface User {
  id: string;
  name: string;
  email?: string;
  age?: number;
}

export interface Admin extends User {
  role: 'admin' | 'super-admin';
}

export type UserList = User[];

export type Status = 'active' | 'archived';
