// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec> --client

import { z } from 'zod';

import { StatusSchema, auth_UserSchema } from './schemas.js';
import type { Status, auth_User } from './types.js';

export interface ZwaggenClientOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  headers?:
    | Record<string, string>
    | (() => Record<string, string>)
    | (() => Promise<Record<string, string>>);
}

export class ZwaggenHttpError extends Error {
  constructor(public response: Response) {
    super(`HTTP ${response.status} ${response.statusText}`);
    this.name = 'ZwaggenHttpError';
  }
}

export function createClient(opts: ZwaggenClientOptions) {
  const f = opts.fetch ?? globalThis.fetch;
  const baseHeaders = async (): Promise<Record<string, string>> => {
    if (typeof opts.headers === 'function') return await opts.headers();
    return opts.headers ?? {};
  };
  return {
    userManagement: {
      async searchUsers(input: {
        body: { query: string; filters?: { status?: Status } };
      }): Promise<auth_User[]> {
        const r = await f(`${opts.baseUrl}/users/search`, {
          method: 'POST',
          headers: { 'content-type': 'application/json', ...(await baseHeaders()) },
          body: JSON.stringify(input.body),
        });
        if (!r.ok) throw new ZwaggenHttpError(r);
        return z.array(auth_UserSchema).parse(await r.json());
      },
    },
  };
}
