// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec>

import { z } from 'zod';

export const auth_UserSchema = z.object({
  id: z.string(),
  email: z.string(),
});
export type auth_User = z.infer<typeof auth_UserSchema>;

export const billing_InvoiceSchema = z.object({
  amount: z.number(),
});
export type billing_Invoice = z.infer<typeof billing_InvoiceSchema>;

export const StatusSchema = z.enum(['active', 'archived']);
export type Status = z.infer<typeof StatusSchema>;
