// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec> --client

import { z } from 'zod';

import { UserSchema } from './schemas.js';
import type { User } from './types.js';

export interface ZwaggenClientOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  headers?:
    | Record<string, string>
    | (() => Record<string, string>)
    | (() => Promise<Record<string, string>>);
}

export class ZwaggenHttpError extends Error {
  constructor(public response: Response) {
    super(`HTTP ${response.status} ${response.statusText}`);
    this.name = 'ZwaggenHttpError';
  }
}

export function createClient(opts: ZwaggenClientOptions) {
  const f = opts.fetch ?? globalThis.fetch;
  const baseHeaders = async (): Promise<Record<string, string>> => {
    if (typeof opts.headers === 'function') return await opts.headers();
    return opts.headers ?? {};
  };
  return {
    users: {
      async listUsers(): Promise<User[]> {
        const r = await f(`${opts.baseUrl}/users`, { method: 'GET', headers: await baseHeaders() });
        if (!r.ok) throw new ZwaggenHttpError(r);
        return z.array(UserSchema).parse(await r.json());
      },
      async getUser(input: { id: string }): Promise<User> {
        const r = await f(`${opts.baseUrl}/users/${encodeURIComponent(input['id'])}`, {
          method: 'GET',
          headers: await baseHeaders(),
        });
        if (!r.ok) throw new ZwaggenHttpError(r);
        return UserSchema.parse(await r.json());
      },
      async createUser(input: { body: User }): Promise<User> {
        const r = await f(`${opts.baseUrl}/users`, {
          method: 'POST',
          headers: { 'content-type': 'application/json', ...(await baseHeaders()) },
          body: JSON.stringify(input.body),
        });
        if (!r.ok) throw new ZwaggenHttpError(r);
        return UserSchema.parse(await r.json());
      },
      async searchUsers(
        input: { q: string; limit?: number } & { 'X-Request-Id': string },
      ): Promise<User[]> {
        const r = await f(
          (() => {
            const qs = new URLSearchParams();
            if (input['q'] !== undefined) qs.set('q', String(input['q']));
            if (input['limit'] !== undefined) qs.set('limit', String(input['limit']));
            const q = qs.toString();
            return `${opts.baseUrl}/users/search${q ? '?' + q : ''}`;
          })(),
          {
            method: 'GET',
            headers: { ...(await baseHeaders()), 'X-Request-Id': input['X-Request-Id'] },
          },
        );
        if (!r.ok) throw new ZwaggenHttpError(r);
        return z.array(UserSchema).parse(await r.json());
      },
    },
  };
}
