import { describe, it, expect } from 'vitest';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { fromJSON } from '@zwaggen/core';
import { generateTs } from '../../src/generate/types.js';
import { format } from '../../src/generate/format.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

async function loadFixtureSpec() {
  const raw = await readFile(join(__dirname, 'fixtures/codegen-fixture.json'), 'utf8');
  return fromJSON(JSON.parse(raw));
}

async function loadExpected() {
  return readFile(join(__dirname, 'fixtures/expected-types.ts'), 'utf8');
}

describe('generateTs', () => {
  it('matches the frozen fixture output exactly', async () => {
    const spec = await loadFixtureSpec();
    const out = await format(generateTs(spec));
    const expected = await loadExpected();
    expect(out).toBe(expected);
  });

  it('emits an interface per object type', async () => {
    const spec = await loadFixtureSpec();
    const out = generateTs(spec);
    expect(out).toContain('export interface User');
    expect(out).toContain('export interface Admin');
  });

  it('marks optional fields with `?`', async () => {
    const spec = await loadFixtureSpec();
    const out = generateTs(spec);
    expect(out).toMatch(/email\?: string/);
    expect(out).toMatch(/age\?: number/);
  });

  it('flattens extends via TS interface inheritance', async () => {
    const spec = await loadFixtureSpec();
    const out = generateTs(spec);
    expect(out).toMatch(/export interface Admin extends User/);
  });

  it('emits literal unions correctly', async () => {
    const spec = await loadFixtureSpec();
    const out = generateTs(spec);
    expect(out).toMatch(/role:\s*'admin'\s*\|\s*'super-admin'/);
  });

  it('emits array aliases', async () => {
    const spec = await loadFixtureSpec();
    const out = generateTs(spec);
    expect(out).toMatch(/export type UserList = User\[\]/);
  });

  it('emits standalone union aliases', async () => {
    const spec = await loadFixtureSpec();
    const out = generateTs(spec);
    expect(out).toMatch(/export type Status =\s*'active'\s*\|\s*'archived'/);
  });

  it('starts with auto-generated header', async () => {
    const spec = await loadFixtureSpec();
    const out = generateTs(spec);
    expect(out.startsWith('// AUTO-GENERATED by zwag')).toBe(true);
  });
});

describe('generateTs — folder-key sanitization', () => {
  it('rewrites top-level names AND ref/extends targets that contain a slash', async () => {
    const baseSpec = await loadFixtureSpec();
    const spec = {
      ...baseSpec,
      types: {
        'auth/User': {
          kind: 'object',
          fields: [{ name: 'id', required: true, type: { kind: 'string' } }],
        },
        Admin: {
          kind: 'object',
          extends: ['auth/User'],
          fields: [{ name: 'role', required: true, type: { kind: 'string' } }],
        },
        UserList: { kind: 'array', element: { kind: 'ref', ref: 'auth/User' } },
      },
      endpoints: [],
    } as typeof baseSpec;
    const out = generateTs(spec);
    expect(out).toContain('export interface auth_User {');
    expect(out).toContain('export interface Admin extends auth_User {');
    expect(out).toContain('export type UserList = auth_User[];');
    expect(out).not.toContain('auth/User');
  });

  it('throws on collision when two keys sanitize to the same name', async () => {
    const baseSpec = await loadFixtureSpec();
    const spec = {
      ...baseSpec,
      types: {
        'auth/User': { kind: 'object', fields: [] },
        auth_User: { kind: 'object', fields: [] },
      },
      endpoints: [],
    } as typeof baseSpec;
    expect(() => generateTs(spec)).toThrow(/collision/i);
  });
});
