import { findIllegalFileTypes } from '../schema/validateFileType';
import type {
  Spec,
  TypeDef,
  ObjectType,
  ObjectField,
  LiteralType,
} from '../schema/types';
import { safeIdentifier, sanitizeFolderKey } from './helpers';
import { detectKeyCollisions } from './ts';

const HEADER = `// AUTO-GENERATED by zwag — do not edit. Regenerate with: zwag generate ts <spec>\n\nimport { z } from 'zod';\n\n`;

function assertNoIllegalFileTypesForZod(spec: Spec): void {
  const errs = findIllegalFileTypes(spec);
  if (errs.length === 0) return;
  throw new Error(
    'Codegen aborted — illegal file type placements:\n' +
      errs.map((e) => `  • ${e.where}: ${e.message}`).join('\n'),
  );
}

export function generateZod(spec: Spec): string {
  assertNoIllegalFileTypesForZod(spec);
  detectKeyCollisions(spec);
  const lines: string[] = [HEADER];
  for (const [name, def] of Object.entries(spec.types)) {
    const safeName = sanitizeFolderKey(name);
    lines.push(emitTopLevel(safeName, def, spec));
    lines.push(`export type ${safeName} = z.infer<typeof ${safeName}Schema>;`);
    lines.push('');
  }
  return lines.join('\n');
}

function emitTopLevel(name: string, def: TypeDef, spec: Spec): string {
  return `export const ${name}Schema = ${zodFor(def, spec, true)};`;
}

function zodFor(def: TypeDef, spec: Spec, topLevelObject = false): string {
  switch (def.kind) {
    case 'string':
      return 'z.string()';
    case 'number':
      return 'z.number()';
    case 'integer':
      return 'z.number().int()';
    case 'boolean':
      return 'z.boolean()';
    case 'null':
      return 'z.null()';
    case 'literal':
      return zodLiteral(def);
    case 'array':
      return `z.array(${zodFor(def.element, spec)})`;
    case 'union':
      return zodUnion(def.variants, spec);
    case 'ref':
      return `${sanitizeFolderKey(def.ref)}Schema`;
    case 'file':
      // Unreachable: validator rejects file types in named-type position.
      // Kept exhaustive to satisfy TS and survive any future schema reshuffle.
      return 'z.instanceof(File)';
    case 'object':
      return zodObject(def, spec, topLevelObject);
  }
}

function zodObject(def: ObjectType, spec: Spec, topLevel: boolean): string {
  const fields = def.fields.map((f) => emitField(f, spec)).join(',\n');
  const body = fields ? `{\n${fields},\n}` : '{}';
  if (topLevel && def.extends && def.extends.length > 0) {
    // First parent is the base; chain .merge() for the rest; .extend() for own fields.
    const base = `${sanitizeFolderKey(def.extends[0]!)}Schema`;
    const merged = def.extends
      .slice(1)
      .reduce((acc, p) => `${acc}.merge(${sanitizeFolderKey(p)}Schema)`, base);
    return `${merged}.extend(${body})`;
  }
  return `z.object(${body})`;
}

function emitField(field: ObjectField, spec: Spec): string {
  const key = safeIdentifier(field.name);
  const inner = zodFor(field.type, spec);
  return `  ${key}: ${field.required ? inner : `${inner}.optional()`}`;
}

function zodLiteral(def: LiteralType): string {
  if (typeof def.value === 'string') return `z.literal('${def.value.replace(/'/g, "\\'")}')`;
  if (typeof def.value === 'number' || typeof def.value === 'boolean')
    return `z.literal(${def.value})`;
  if (def.value === null) return 'z.null()';
  return `z.literal(${JSON.stringify(def.value)})`;
}

function zodUnion(variants: TypeDef[], spec: Spec): string {
  // Special case: all-string-literals → z.enum(...)
  const allStringLits = variants.every(
    (v) => v.kind === 'literal' && typeof (v as LiteralType).value === 'string',
  );
  if (allStringLits) {
    const values = variants.map((v) => `'${(v as LiteralType).value}'`).join(', ');
    return `z.enum([${values}])`;
  }
  const inner = variants.map((v) => zodFor(v, spec)).join(', ');
  return `z.union([${inner}])`;
}
